name = "cymatic-resonance"
pages_build_output_dir = "dist"

[vars]
VITE_SUPABASE_URL = "https://umsgecaeozngdejwvcsu.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtc2dlY2Flb3puZ2Rland2Y3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwNTg4OTIsImV4cCI6MjA5NzYzNDg5Mn0.Zbp6Db69rSBI2egkPt6Puk0vTScVek7wF47HUT02-sQ"
