// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseUrl, getSupabaseAnonKey, getMissingSupabaseEnv } from "../../lib/env";

// recursive proxy for safe dummy client
const createDummyProxy = (path: string[] = []): unknown => {
  const target = () => {
    throw new Error(
      `[Supabase Error] Supabase is not configured (missing env vars: ${getMissingSupabaseEnv().join(", ")}). Cannot call: supabase.${path.join(".")}()`,
    );
  };
  return new Proxy(target, {
    get: (t, prop) => {
      if (typeof prop === "string") {
        return createDummyProxy([...path, prop]);
      }
      return (t as Record<string | symbol, unknown>)[prop];
    },
  });
};

const dummyClient = createDummyProxy() as SupabaseClient<Database>;

function createSupabaseClient(): SupabaseClient<Database> {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_ANON_KEY = getSupabaseAnonKey();

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error(
      `[Supabase Critical] Initialization failed: Missing environment variables (${getMissingSupabaseEnv().join(", ")}). Using dummy client.`,
    );
    return dummyClient;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

// Strictly memoized singleton instance to avoid re-instantiation loops during React re-renders.
let supabaseInstance: SupabaseClient<Database> | null = null;

export const getSupabase = (): SupabaseClient<Database> => {
  if (!supabaseInstance) {
    try {
      supabaseInstance = createSupabaseClient();
    } catch (e) {
      console.error("[Supabase] Failed to create instance:", e);
      return dummyClient;
    }
  }
  return supabaseInstance;
};

// Export the singleton directly for ease of use across the app
export const supabase = getSupabase();
