// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createAdminClient } from "@supabase/server/core";
import type { Database } from "./types";

// Server-side Supabase client - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// This client automatically resolves the admin credentials.
export const supabaseAdmin = createAdminClient<Database>();
